styles: add surveyjs styles
unepwcmc/action-agenda pull request #46
Opened 2022-02-03 16:22 UTC by RainbowGiantSquid

criteria form title and description
page title - hide
page description styling
questions
font sizes
padding

doesn't contain multi-choice icons and styles (need to figure out how to differentiate it from regular description item)

2022-02-03 20:24 UTC, yndajas requested changes
Looking good! This is from a different PR, but perhaps it can be included here - the tooltip font size on the designs seems to be 14px (mostly!), whereas it's 12px here

Other than that, there are just a few small comments on the file

Multiselect styling implemented in latest commit

2022-02-03 20:24 UTC, yndajas commented on app/assets/stylesheets/base/_surveyjs.scss
> +  font-size: rem-calc(20);
Rule order

2022-02-06 14:58 UTC, RainbowGiantSquid commented on app/assets/stylesheets/base/_surveyjs.scss
> +    h5 {
Oh, that's right - I've been silly and trying to put the toltip at the end of each sentence, didn't click that it's a set width! 😅

2022-02-06 15:13 UTC, RainbowGiantSquid commented on app/assets/stylesheets/base/_surveyjs.scss
> +      h5 {
I added max-with in % because it's a bit more responsive, but not for the question so the lat/long labels are not being squashed

2022-02-07 13:21 UTC, yndajas requested changes
Just one outstanding comment on font size, and possibly on the form description (happy to leave it for now though), but otherwise looks good!

2022-02-07 13:21 UTC, yndajas commented on app/assets/stylesheets/base/_surveyjs.scss
> +        .sv-question__description {
Think this still needs updating to 18px font

2022-02-07 13:21 UTC, yndajas commented on app/assets/stylesheets/base/_surveyjs.scss
> +      h5 {
Might still need adjusting - the form description looks a little wider on the criteria form than it is on the designs, but happy to leave it to design review!

<img width="1037" alt="Screenshot 2022-02-07 at 13 11 37" src="https://user-images.githubusercontent.com/40244233/152795265-4ebd5e63-fe91-493e-b2ef-8c3bfbbc6f86.png">

2022-02-07 13:50 UTC, yndajas approved these changes

2022-02-07 13:55 UTC, merged