Ticket31 update db
unepwcmc/action-agenda pull request #8
Opened 2022-01-20 10:57 UTC by sergiomarrocoli

Don't merge until after ticket-10 has been merged 

- Restructures the db and classes to match form requirements, like changing some fields to asssociations (e.g. 'link') and belongs_to to has_many
- Rake tasks to migrate the data to this new structure (e.g. adds the old commitment.country to commitment.countries)
- updates existing importer task to match new data structure

## To check against staging data:

## clear your local db:
bundle exec rake db:drop
bundle exec rake db:create

### download the staging db (you might need to add credentials):
aws s3 ls s3://actionagenda.bkp --recursive --human-readable --summarize
aws s3 cp s3://actionagenda.bkp/staging-db/actiona_agenda_staging.tar.gz action_agenda_copy.tar

### Unzip the file
however you want

### import the data to your db:
psql -U :your_user -d aa_development -f actionagenda_staging.sql

### check these run without errors:
bundle exec rake db:migrate

bundle exec rake migrate_data:add_commitment_country_to_commitment_countries
bundle exec rake migrate_data:add_commitment_link_to_commitment_links
bundle exec rake migrate_data:add_default_options_for_threats
bundle exec rake migrate_data:set_existing_commitments_to_live

### check the site is still working ok
restart webacker and server, click around

I would also reset your db in the normal way, run seeds and the importer to check that still works

2022-01-20 18:10 UTC, yndajas requested changes
Just a few typos and format comments, plus a couple of queries on associations

2022-01-20 18:10 UTC, yndajas commented on lib/tasks/migrate_data.rake
> +    puts failed_to_set_live.empty? ? "All commitments set to 'live'." : "Commitements #{ failed_to_set_live.join(', ')} could not be set to live"
Typo in end of ternary statement: "Commitements"

2022-01-20 18:10 UTC, yndajas commented on test/fixtures/commitments.yml
> +  stage: 'Committed'
Mixture of single quotes and no quotes

2022-01-21 09:03 UTC, sergiomarrocoli commented on app/models/link.rb
> +  has_and_belongs_to_many :commitments
you're right, should just be has_many and belongs_to

2022-01-21 11:59 UTC, yndajas approved these changes

2022-01-21 12:01 UTC, merged